### ISSUE TITLE
Melhorias no uso do pacote

### ISSUE THREAD

**Issue by RogerBrusamarello** [Nucleus-Inc/day_schedule_list#19]
1- Poderia deixar os parâmetros de criar, aumenta/diminuir (resize) ,atualizar e período indisponíveis como opcionais. Assim posso apenas utilizar o layout para inserir meus registros. Sem precisar fazer um fork para poder atender a necessidade de apenas visualização.

2- Poderia utilizar também outros formatos como toISOString ou DateTime em vez de apenas o TimeOfDay.

3- Poderia ter um parâmetro  de inicio do horário e final, assim ficaria mais fácil de passar para o componente que deve começar às 7:00 até às 22:00.

Estou utilizando o pacote para listar os atendimentos de um salão de beleza. Porém seria apenas para visualização, a edição dos  horários seriam apenas feitas por outro sistema.

**Comment by josechagas** [comment]
1- A funcionalidade de somente visualização parece super válida, vou trabalhar para adicionar na próxima versão

2- A agenda é diária sendo assim receber DateTime ou o ISO8601 apenas adicionaria uma maior complexidade de tratamento, o meu conselho para essa situação é que você crie [extensões](https://dart.dev/guides/language/extension-methods) para automaticamente realizar as conversões.

3- O formato atual além de ser bem customizável atende da mesma maneira.
